services:
  front:
    hostname: front-container
    build:
      context: ./docker/front
      dockerfile: Dockerfile-front
      # build用変数
      args:
        FRONT_UID: ${UID}
        FORNT_GID: ${GID}
    tty: true
    ports:
      - 127.0.1.2:${FRONT_PUBLIC_PORT}:3000
    user: ${UID}:${GID}
    volumes:
      - ./src:/home/node/next
    # hostsに記述
    extra_hosts:
      - "somehost:162.242.195.82"
      - "otherhost:50.31.209.229"
    deploy:
      resources:
        # 確保
        reservations:
          cpus: '0.25' # コア数
          memory: 20M
          
        # 上限
        limits:
          cpus: '0.50'
          memory: 50M
          # pids: 20 // 初期、13くらいあるな
#     secrets:
#       - my_secret

# secrets:
#   my_secret:
#     file: my_secret.txt